### ISSUE TITLE
External script does not work on files in group folders.

### ISSUE THREAD

**Issue by ernolf** [nextcloud/workflow_script#38] opened 2020-02-10 13:04 UTC
Everything said by title.

**Comment by jonas154** [comment] 2020-04-09 13:14
having the same problem. I think the issue occurs when:

User A shares a folder with User B. When User B uploads now a file, %n gives its relative upload path (but not the path to the file itself as it is under the path of user A)

**Comment by jurgenhaas** [comment] 2020-09-20 08:19
Same issue here.

**Comment by k1l1** [comment] 2020-10-16 12:21
Duplicate of #48

**Comment by Pingger** [comment] 2020-10-16 12:29
> 
> 
> Duplicate of #48

No. Shared folders do trigger workflow scripts. 

**GROUP FOLDERS DON'T EVEN TRIGGER**. Your "workaround" does not even remotely solve this.

So again to be clear: Not a duplicate

**Comment by k1l1** [comment] 2020-10-16 12:34
Ok, then its a different story there.

**Comment by ostasevych** [comment] 2023-07-13 16:51
Hi! So, are any news on group folders?

**Comment by Nils160988** [comment] 2023-11-14 09:24
Changes in group folders do trigger flows for me (NC 27.1.3), so I would expect this issue to be resolved here. Can someone comment if this issue is still valid?

**Comment by ostasevych** [comment] 2023-11-14 12:13
> Changes in group folders do trigger flows for me (NC 27.1.3), so I would expect this issue to be resolved here. Can someone comment if this issue is still valid?

Still valid.

**Comment by blizzz** [comment] 2023-11-15 13:37
Proposed fix in #218

**Closed** 2023-11-16 11:26 UTC
Labels: needs info
