### ISSUE TITLE
Wrong parameter value for workflow script -- again

### ISSUE THREAD

**Issue by it25fg** [nextcloud/workflow_script#111] opened 2022-02-04 11:57 UTC
After updating to NC 21.0.7, the problem described in https://github.com/nextcloud/workflow_script/issues/79 appears again: a workflow script gets a file path starting with '/tmp' as parameter %n.

workflow_scripts app has version 1.6.0

It seems to me that patch https://github.com/nextcloud/workflow_script/pull/81 is not contained in this app version. (I only checked for the presence of the additional file being added by the patch: lib/Exception/ParameterNotSubstituted.php)

Looking at the source here in github, I see the patch present in the branches stable19, stable20 and stable21. But I don't know exactly where a nextcloud instance fetches its apps and their updates. In my opinion, something got lost between source repo and download server.

Out of curiosity, I tried to apply the patch to the 1.6.0 version -- unfortunately it does not match anymore (only tried with default fuzziness).

How can we solve this?

**Comment by joshtrichards** [comment] 2023-06-29 19:17
Hi @it25fg: Thanks for the report.

It looks like #81 came after v1.6.0 was released. it was backported to what was intended for NC21 in #84. Unfortunately a new release after v1.6.0 was never published for NC21. Instead the next release (v1.7.0) was set to require NC22. And by the time you reported this (2/2022) NC21 was basically EOL.

It's definitely in there now, so I think we can safely close this out.

**Comment by blizzz** [comment] 2023-06-29 21:26
Thanks for the evaluation @joshtrichards!

**Closed by blizzz** 2023-06-29 21:26 UTC
