### ISSUE TITLE
File deleted script is not triggered

### ISSUE THREAD

**Issue by gftrotta** [nextcloud/workflow_script#80] opened 2021-02-06 12:34 UTC
## Steps to reproduce
1. Create external scripts
2. Select "file deleted"
3. Filtered with request time from 00:00 to 23:59

The script is a bash script that run a curl command to request a resource from a server.
When I select "File Create" the script is triggered. When I select "File deleted" the script is not triggered.

### Expected behaviour
A script should be run

### Actual behaviour
The script is not triggered

## Workflow Script app

**Workflow Script app version:** 1.5.1

## Server configuration

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4.15

**Nextcloud Version:** 20.0.6/20.0/19.0

**Where did you install Nextcloud from:** nextcloud docker 

**Signing status:**

No errors have been found.

**List of activated apps:**

**Nextcloud configuration:**

<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'overwritehost' => 'localhost:80',
  'overwriteprotocol' => 'http',
  'overwritewebroot' => '/nextcloud',
  'instanceid' => 'ocjc1r7ao4qq',
  'passwordsalt' => 'ErP0lgBD/7c6lmJ+sBXxs4TCGyh2Oq',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => '***',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '20.0.6.1',
  'overwrite.cli.url' => 'http://***/***',
  'dbname' => '***',
  'dbhost' => '***',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '***',
  'dbpassword' => '***',
  'installed' => true,
);

**Are you using encryption:** no

### Server log (data/nextcloud.log)
{"reqId":"GAqB0n37yt1RrcUsry2O","level":3,"time":"2021-02-06T11:46:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"RwC08sKfEMV4st7kEIRi","level":3,"time":"2021-02-06T11:47:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"VsD3qulhOcWTV2LKcWQD","level":3,"time":"2021-02-06T11:48:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"wpJ1dBT4XWhwV29DikZ3","level":3,"time":"2021-02-06T11:49:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"i4yWJSbJfEZ19rCGkxdb","level":2,"time":"2021-02-06T11:49:09+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"i4yWJSbJfEZ19rCGkxdb","level":2,"time":"2021-02-06T11:49:09+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"orOFiY1zzaAmfPgr69aQ","level":3,"time":"2021-02-06T11:50:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"q7sUZb01dVa9sZosoCA0","level":3,"time":"2021-02-06T11:51:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"9AhKGDCGyIkqPyMlz6PW","level":3,"time":"2021-02-06T11:52:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"EnJ0CvgNWjaAAPJFV1Xx","level":3,"time":"2021-02-06T11:53:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"RjoDE8vr7H61XuP188Lb","level":3,"time":"2021-02-06T11:54:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"Y7RyMHNfLpRx3255Zs5g","level":2,"time":"2021-02-06T11:54:08+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"Y7RyMHNfLpRx3255Zs5g","level":2,"time":"2021-02-06T11:54:08+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"ycPQHLUjyXbiyXY4bJ54","level":2,"time":"2021-02-06T11:54:09+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"ycPQHLUjyXbiyXY4bJ54","level":2,"time":"2021-02-06T11:54:09+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"MLvdCPWXat0f6xl4NHZD","level":2,"time":"2021-02-06T11:54:09+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"MLvdCPWXat0f6xl4NHZD","level":2,"time":"2021-02-06T11:54:09+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"Aw1MmjPk52kgW595NQWC","level":2,"time":"2021-02-06T11:54:15+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"Aw1MmjPk52kgW595NQWC","level":2,"time":"2021-02-06T11:54:15+00:00","remoteAddr":"172.25.0.4","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36","version":""}
{"reqId":"0ijaI4lRkTo4K90V3GVE","level":3,"time":"2021-02-06T11:55:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"/nextcloud/cron.php","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":653,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":1091,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/cron.php","line":42,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/base.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":"20.0.6.1"}

**Comment by WaferJay** [comment] 2021-02-23 15:28
Same issue here. Filtered with filename, but the command is not triggered whether the file is moved to trashbin or permanently deleted. I just want to permanently delete some files automatically. Other rules works well.

**Comment by ThePatzen** [comment] 2021-04-29 07:26
Same issue here!

**Comment by radoeka** [comment] 2023-08-19 12:48
Is this still not working?  In the meantime, I think that Nextcloud had multiple major releases.

If it is working close the bug report, if not update the report, please.

**Comment by blizzz** [comment] 2023-11-21 10:59
Cannot reproduce, a delete actions triggers just fine for me.

**Comment by ts-mk** [comment] 2024-12-15 12:09
I run into the issue of file deleted condition not working but in my case it was due to a combination with a "File system tag" condition. This seems to be a problem in the Nextcloud itself ([#49720](https://github.com/nextcloud/server/issues/49720)). When the file deleted condition is used by itself, it is working fine.

**Comment by blizzz** [comment] 2024-12-17 10:47
Closing in favor of https://github.com/nextcloud/server/issues/49720

**Closed by blizzz** 2024-12-17 10:47 UTC
Labels: bug, needs info
